name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:5.0

    steps:
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: csharp
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: dotnet restore Courier.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore Courier.csproj
    - name: Test
      run: dotnet test --configuration Release --no-restore --no-build --verbosity normal Courier.csproj
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
